services:
  hubioinfo-full:
    image: hubioinfows/full_env:latest
    build:
      context: .
      dockerfile: hu_bioinfo_full.Dockerfile
    container_name: dev-hubioinfows-full-container
    environment:
      - DISABLE_AUTH=true
      - CACHE_DIR=/home/ubuntu/cache
      - PROJ_DIR=/home/ubuntu/proj
      - GITHUB_PAT=YOUR_GITHUB_PAT
    volumes:
      - ../projects:/home/ubuntu/proj
      - ../../cache:/home/ubuntu/cache
      - ../../cache/TinyTeX:/home/ubuntu/.TinyTeX
    ports:
      - 8080:8080
    command: sleep infinity
    init: true
